# NumPy Preliminaries

In this notebook, we'll cover the basics of NumPy:

- **Arrays:** How to create and work with NumPy arrays.
- **Indexing & Slicing:** How to access and manipulate array elements.
- **Masking (Boolean Indexing):** How to select elements based on conditions.

NumPy is a powerful library for numerical computing in Python, and these concepts are essential for many data science and robotics applications.

In [79]:
# We can import Numpy here. About 100% of the time that people use numpy they call it 'np'
import numpy as np


# Placeholder
your_code_here = lambda: None

## 1. Creating Arrays

NumPy arrays are the core data structure. You can create them from lists or using built-in functions.

In [80]:
# Create a 1D array from a list
a = np.array([1, 2, 3, 4, 5])
print("1D array:", a)
print("Shape:", a.shape)

# Create a 2D array from nested lists
b = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D array:\n", b)
print("Shape:", b.shape)

# Create arrays with built-in functions
zeros = np.zeros((3, 4))
ones = np.ones((2, 5))
range_array = np.arange(0, 10, 2)  # From 0 to 8 with step 2
linspace_array = np.linspace(0, 1, 5)  # 5 numbers between 0 and 1

print("\nZeros:\n", zeros)
print("\nOnes:\n", ones)
print("\nArange:", range_array)
print("\nLinspace:", linspace_array)

1D array: [1 2 3 4 5]
Shape: (5,)

2D array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Arange: [0 2 4 6 8]

Linspace: [0.   0.25 0.5  0.75 1.  ]


In [81]:
## Now try a couple things to test knowledge.

# Challenge 1: Create an array that is 10x10, all zeros

zeros = np.zeros((10, 10))
print("\nZeros:\n", zeros)

# Challenge 2: Create an array that is all the integers divisible by 3 between 0 and 100.

threeArray = np.arange(0, 100, 3)
print("\nThrees\n", threeArray)

# Challenge 2: Create a matrix that looks like this (without typing it out!)
# You'll probably want to google np.reshape()!
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

numArray = np.arange(1, 10, 1)
shape_array = numArray.reshape(3, 3)
print("\nZeros:\n", shape_array)



Zeros:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

Threes
 [ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]

Zeros:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## 2. Indexing and Slicing

You can access elements in an array using indexing and slicing. 

- **Indexing:** Access a specific element.
- **Slicing:** Extract a sub-array.

Note that indexing is zero-based.

In [82]:
# 1D array indexing and slicing
print("First element of a:", a[0])
print("Elements 2 to 4 of a:", a[1:4])

# 2D array indexing
print("\nElement at row 1, column 2 of b:", b[1, 2])
print("First row of b:", b[0])
print("Last column of b:", b[:, -1])

# Skipping elements:
print("Every other value of a:", a[::2])
print("Every third value of a:", a[::3])

First element of a: 1
Elements 2 to 4 of a: [2 3 4]

Element at row 1, column 2 of b: 6
First row of b: [1 2 3]
Last column of b: [3 6]
Every other value of a: [1 3 5]
Every third value of a: [1 4]


In [83]:
## Now some things to try again!

# Challenge 1: Create an array that is every integer between 1 and 100 (hint: use np.arange). 
# Then index it to only keep the numbers divisible by 5.
arr = np.arange(0, 100, 1)
print("\nZeros:\n", arr[::5])

# Challenge 2: Take this matrix and index it to create a 1D array of 10 1s.
input_matrix = np.eye(10) # print this to see what it is
one_array = input_matrix



Zeros:
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]

Zeros:
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


## 3. Boolean Indexing (Masking)

Boolean indexing (masking) lets you select elements that satisfy a condition.

For example, say we want to get rid of every element in a list that is below some value (in this case 18).

We can first create a `mask` that is the same size as the array, and is `True` if each entry is greater than 18 and `False` otherwise.

In [84]:
# Create an array for demonstration
c = np.array([10, 15, 20, 25, 30])
print("Array c:", c)

# Create a boolean mask (True for elements greater than 18)
mask = c > 18
print("Boolean mask (c > 18):", mask)

# Use the mask to filter array elements
filtered = c[mask]
print("Filtered array (elements > 18):", filtered)

Array c: [10 15 20 25 30]
Boolean mask (c > 18): [False False  True  True  True]
Filtered array (elements > 18): [20 25 30]


## 4. Combining Operations

You can combine slicing and masking for more advanced selections.

In [85]:
# Create a 2D array
d = np.random.rand(4, 4)*10
print("2D array d:\n", d)

# Select all rows where the element in the first column is greater than 5
row_mask = d[:, 0] > 4
print("\n\nRow mask (first column > 4):", row_mask)

selected_rows = d[row_mask]
print("\n\nSelected rows:\n", selected_rows)

# Now that we have a mask, we can replace values at the selected locations with another value:
d[row_mask] = -1 # For selected rows, set the selected values to -1.
print("\n\nd with elements from selected rows set to 0", d)

# Within these rows, select only elements that are even numbers (when rounded to the nearest int!)
even_mask = selected_rows.astype(int) % 2 == 0
print("\n\nEven mask on selected rows:\n", even_mask)

even_elements = selected_rows[even_mask]
print("\n\nEven elements from selected rows:", even_elements)


2D array d:
 [[0.80611449 1.87518818 2.42166061 1.95282882]
 [3.91561865 7.65907498 8.97861164 4.08916501]
 [5.78718633 2.63010791 6.68860449 8.28863629]
 [0.87613505 1.99216594 8.84477082 1.91038802]]


Row mask (first column > 4): [False False  True False]


Selected rows:
 [[5.78718633 2.63010791 6.68860449 8.28863629]]


d with elements from selected rows set to 0 [[ 0.80611449  1.87518818  2.42166061  1.95282882]
 [ 3.91561865  7.65907498  8.97861164  4.08916501]
 [-1.         -1.         -1.         -1.        ]
 [ 0.87613505  1.99216594  8.84477082  1.91038802]]


Even mask on selected rows:
 [[False  True  True  True]]


Even elements from selected rows: [2.63010791 6.68860449 8.28863629]


In [86]:
## Final Challenge: Given the below random matrix, keep values where each 
# element is greater than 3 but less than 5. Set all the other values to zero.

e = np.random.rand(10,10)*10 # random 10x10 array 
print("2D array e:\n", e)




2D array e:
 [[9.05180247 0.36070967 8.09423988 1.93341132 7.50000777 0.45103703
  6.70722359 7.96021567 9.79245951 1.88856561]
 [3.91213106 9.51850664 6.63964183 6.59468546 0.70962698 2.00440157
  9.99462623 7.98769727 8.00435518 3.29413976]
 [5.38455906 9.67594432 6.79356095 1.60025756 0.19712075 6.45646224
  8.48751545 5.18253589 7.78222598 0.745422  ]
 [5.85137416 7.17735268 9.73237449 3.96800849 1.91035045 4.36475787
  4.85627418 7.95234601 9.17075482 7.35416381]
 [8.04758189 0.71696543 9.99752618 2.38303986 7.98242662 2.8742674
  8.6357224  0.20716288 4.99716876 6.03824763]
 [0.60794648 6.23602506 5.48241246 7.97248636 6.63562975 7.10493091
  2.94587826 7.3973097  9.3824129  6.43405635]
 [2.86867777 9.98821617 5.64102143 6.29127276 7.8463187  2.460749
  3.40225343 5.44370089 7.49029797 8.82382681]
 [4.99052196 6.46522381 2.62798618 5.93943138 7.92234177 4.21166444
  6.56283651 8.6122726  3.91485674 3.47827719]
 [7.29832881 0.69006136 7.2923871  5.33497403 6.95185895 7.27011271
  

## Summary

In this notebook you learned:

- How to create NumPy arrays from lists and using built-in functions.
- How to access elements using indexing and slicing.
- How to use boolean indexing (masking) to filter arrays.

These are foundational skills that will help you work with numerical data efficiently.

Try modifying the code examples and see how changes affect the output. Happy coding!